/**
 * The HTML document shell, authored in TypeScript.
 *
 * Vite needs an `index.html` on disk to use as its Rollup entry, but keeping
 * one as hand-written source put the app's `<head>` outside the React tree,
 * where the theme colour and title could drift from the design system. This
 * module is the single definition; `vite-plugins/aera-document.ts` renders it
 * to `index.html` at build time.
 */

import { palette } from './design-system/colors';

export interface DocumentOptions {
  title?: string;
  /** Module entry, relative to the project root. */
  entry?: string;
}

/**
 * Render the document.
 *
 * Kept deliberately small: everything except the mount point and the theme
 * colour belongs in React, not here.
 */
export function renderDocument({
  title = 'AERA',
  entry = '/src/index.tsx',
}: DocumentOptions = {}): string {
  return `<!DOCTYPE html>
<!--
  Generated by vite-plugins/aera-document.ts from src/document.ts.
  Do not edit: this file is rewritten on every build.
-->
<html lang="en" class="dark">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/png" href="./favicon.png" />
    <link rel="apple-touch-icon" href="./icon-256.png" />
    <meta name="theme-color" content="${palette.bg.base}" />
    <title>${title}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="${entry}"></script>
  </body>
</html>
`;
}
