# MADE By Manoj Dahal
# Copyright (c) 2026 Manoj Dahal. All rights reserved.
# Contact: info@manoj-dahal.com.np
# AERA — Artificial Enhanced Reasoning Assistant

"""Language packs: South Asia, East Asia, the Middle East and Africa.

The Indic group is the reason ``TensRule.LISTED`` exists. Hindi, Nepali,
Bengali, Marathi, Gujarati and Punjabi do not compose 21-99 from a tens word
and a ones word -- 87 is सत्तासी in Hindi and सतासी in Nepali, and neither
derives from अस्सी/असी (eighty) plus सात (seven) by any rule a program can
apply. Each of them lists all hundred forms.

They also group large numbers by lakh (10^5) and crore (10^7) rather than by
thousand, so 2,500,000 is "पच्चीस लाख", not "two point five million".
"""

from __future__ import annotations

from .engine import Emotion
from .languages import LanguagePack, TensRule

#: Hindi 0-99. Devanagari forms from standard counting tables; every value in
#: 21-99 is irregular, which is why they are written out.
_HINDI_ONES = (
    "शून्य", "एक", "दो", "तीन", "चार", "पाँच", "छह", "सात", "आठ", "नौ",
    "दस", "ग्यारह", "बारह", "तेरह", "चौदह", "पंद्रह", "सोलह", "सत्रह", "अठारह", "उन्नीस",
    "बीस", "इक्कीस", "बाईस", "तेईस", "चौबीस", "पच्चीस", "छब्बीस", "सत्ताईस", "अट्ठाईस", "उनतीस",
    "तीस", "इकतीस", "बत्तीस", "तैंतीस", "चौंतीस", "पैंतीस", "छत्तीस", "सैंतीस", "अड़तीस", "उनतालीस",
    "चालीस", "इकतालीस", "बयालीस", "तैंतालीस", "चौवालीस", "पैंतालीस", "छियालीस", "सैंतालीस", "अड़तालीस", "उनचास",
    "पचास", "इक्यावन", "बावन", "तिरपन", "चौवन", "पचपन", "छप्पन", "सत्तावन", "अट्ठावन", "उनसठ",
    "साठ", "इकसठ", "बासठ", "तिरसठ", "चौंसठ", "पैंसठ", "छियासठ", "सड़सठ", "अड़सठ", "उनहत्तर",
    "सत्तर", "इकहत्तर", "बहत्तर", "तिहत्तर", "चौहत्तर", "पचहत्तर", "छिहत्तर", "सतहत्तर", "अठहत्तर", "उनासी",
    "अस्सी", "इक्यासी", "बयासी", "तिरासी", "चौरासी", "पचासी", "छियासी", "सत्तासी", "अठासी", "नवासी",
    "नब्बे", "इक्यानवे", "बानवे", "तिरानवे", "चौरानवे", "पचानवे", "छियानवे", "सत्तानवे", "अट्ठानवे", "निन्यानवे",
)

#: Nepali 0-99. Distinct from Hindi throughout: 2 is दुई not दो, 87 is सतासी
#: not सत्तासी, 52 is बाउन्न not बावन.
_NEPALI_ONES = (
    "शून्य", "एक", "दुई", "तीन", "चार", "पाँच", "छ", "सात", "आठ", "नौ",
    "दश", "एघार", "बाह्र", "तेह्र", "चौध", "पन्ध्र", "सोह्र", "सत्र", "अठार", "उन्नाइस",
    "बीस", "एक्काइस", "बाइस", "तेइस", "चौबीस", "पच्चीस", "छब्बीस", "सत्ताइस", "अट्ठाइस", "उनन्तीस",
    "तीस", "एकतीस", "बत्तीस", "तेत्तीस", "चौँतीस", "पैँतीस", "छत्तीस", "सैँतीस", "अठतीस", "उनन्चालीस",
    "चालीस", "एकचालीस", "बयालीस", "त्रिचालीस", "चवालीस", "पैँतालीस", "छयालीस", "सतचालीस", "अठचालीस", "उनन्चास",
    "पचास", "एकाउन्न", "बाउन्न", "त्रिपन्न", "चवन्न", "पचपन्न", "छपन्न", "सन्ताउन्न", "अन्ठाउन्न", "उनन्साठी",
    "साठी", "एकसट्ठी", "बयसट्ठी", "त्रिसट्ठी", "चौसट्ठी", "पैँसट्ठी", "छयसट्ठी", "सतसट्ठी", "अठसट्ठी", "उनन्सत्तरी",
    "सत्तरी", "एकहत्तर", "बहत्तर", "त्रिहत्तर", "चौहत्तर", "पचहत्तर", "छयहत्तर", "सतहत्तर", "अठहत्तर", "उनासी",
    "असी", "एकासी", "बयासी", "त्रियासी", "चौरासी", "पचासी", "छयासी", "सतासी", "अठासी", "उनान्नब्बे",
    "नब्बे", "एकान्नब्बे", "बयानब्बे", "त्रियानब्बे", "चौरानब्बे", "पन्चानब्बे", "छयानब्बे", "सन्तानब्बे", "अन्ठानब्बे", "उनान्सय",
)

#: Lakh and crore. Used across the subcontinent, and the reason a
#: thousand-based scale table reads wrong there.
_INDIC_SCALES = ((10_000_000, "करोड"), (100_000, "लाख"), (1_000, "हजार"))

HINDI = LanguagePack(
    code="hi",
    label="Hindi",
    endonym="हिन्दी",
    # "ना" was here and matched inside "नाम" (name). Removed: the standalone
    # prohibitive is मत, and नहीं covers the rest.
    negations=("नहीं", "मत", "बिना", "कभी नहीं", "ना ही"),
    intensifiers=("बहुत", "अत्यंत", "पूरी तरह", "काफी", "बेहद"),
    hedges=("शायद", "संभवतः", "लगता है", "कदाचित"),
    clause_breaks=("लेकिन", "परंतु", "मगर", "फिर भी", "हालांकि"),
    cues={
        Emotion.EXCITED: ("अद्भुत", "शानदार", "बढ़िया", "उत्कृष्ट"),
        Emotion.HAPPY: ("अच्छा", "धन्यवाद", "सफल", "खुश", "ठीक हो गया", "काम कर रहा"),
        Emotion.CONFIDENT: ("निश्चित", "पक्का", "पुष्टि", "बेशक"),
        Emotion.CURIOUS: ("दिलचस्प", "जिज्ञासु"),
        Emotion.CALM: ("शांत", "स्थिर"),
        Emotion.CONCERNED: ("सावधान", "खतरा", "जोखिम", "चेतावनी"),
        Emotion.SERIOUS: ("गंभीर", "जरूरी", "सुरक्षा", "भेद्यता"),
        Emotion.SAD: ("क्षमा", "माफ", "विफल", "त्रुटि", "टूटा", "दुर्भाग्य", "खराब"),
    },
    ones=_HINDI_ONES,
    tens=(),
    tens_rule=TensRule.LISTED,
    hundred="सौ",
    scales=((10_000_000, "करोड़"), (100_000, "लाख"), (1_000, "हज़ार")),
    point="दशमलव",
    units={"%": ("प्रतिशत", "प्रतिशत"), "ms": ("मिलीसेकंड", "मिलीसेकंड"),
           "gb": ("गीगाबाइट", "गीगाबाइट"), "mb": ("मेगाबाइट", "मेगाबाइट")},
)

NEPALI = LanguagePack(
    code="ne",
    label="Nepali",
    endonym="नेपाली",
    negations=("छैन", "होइन", "नगर", "बिना", "कहिल्यै छैन", "भएन"),
    intensifiers=("धेरै", "अत्यन्तै", "पूर्ण रूपमा", "निकै"),
    hedges=("सायद", "होला", "लाग्छ"),
    clause_breaks=("तर", "यद्यपि", "तैपनि", "जबकि"),
    cues={
        Emotion.EXCITED: ("अद्भुत", "उत्कृष्ट", "राम्रो", "अति राम्रो"),
        Emotion.HAPPY: ("धन्यवाद", "सफल", "खुसी", "मिल्यो", "काम गर्यो"),
        Emotion.CONFIDENT: ("निश्चित", "पक्का", "पुष्टि"),
        Emotion.CURIOUS: ("रोचक", "जिज्ञासा"),
        Emotion.CALM: ("शान्त", "स्थिर"),
        Emotion.CONCERNED: ("होसियार", "जोखिम", "खतरा", "चेतावनी"),
        Emotion.SERIOUS: ("गम्भीर", "जरुरी", "सुरक्षा"),
        Emotion.SAD: ("माफ", "असफल", "त्रुटि", "बिग्रियो", "दुर्भाग्य", "हरायो"),
    },
    ones=_NEPALI_ONES,
    tens=(),
    tens_rule=TensRule.LISTED,
    hundred="सय",
    scales=_INDIC_SCALES,
    point="दशमलव",
    units={"%": ("प्रतिशत", "प्रतिशत"), "ms": ("मिलिसेकेन्ड", "मिलिसेकेन्ड"),
           "gb": ("गिगाबाइट", "गिगाबाइट"), "mb": ("मेगाबाइट", "मेगाबाइट")},
)

MARATHI = LanguagePack(
    code="mr",
    label="Marathi",
    endonym="मराठी",
    negations=("नाही", "नको", "कधीच नाही", "विना"),
    intensifiers=("खूप", "अत्यंत", "पूर्णपणे", "फार"),
    hedges=("कदाचित", "बहुधा", "वाटते"),
    clause_breaks=("पण", "परंतु", "तरीही", "मात्र"),
    cues={
        Emotion.EXCITED: ("अप्रतिम", "जबरदस्त", "उत्कृष्ट"),
        Emotion.HAPPY: ("चांगले", "धन्यवाद", "यशस्वी", "आनंद", "दुरुस्त"),
        Emotion.CONFIDENT: ("निश्चित", "पक्के", "खात्री"),
        Emotion.CURIOUS: ("मनोरंजक", "उत्सुक"),
        Emotion.CALM: ("शांत", "स्थिर"),
        Emotion.CONCERNED: ("सावधान", "धोका", "इशारा"),
        Emotion.SERIOUS: ("गंभीर", "तातडीचे", "सुरक्षा"),
        Emotion.SAD: ("माफ करा", "अयशस्वी", "त्रुटी", "तुटले", "दुर्दैवाने"),
    },
    ones=("शून्य", "एक", "दोन", "तीन", "चार", "पाच", "सहा", "सात", "आठ", "नऊ",
          "दहा", "अकरा", "बारा", "तेरा", "चौदा", "पंधरा", "सोळा", "सतरा", "अठरा", "एकोणीस",
          "वीस"),
    tens=("", "", "वीस", "तीस", "चाळीस", "पन्नास", "साठ", "सत्तर", "ऐंशी", "नव्वद"),
    tens_rule=TensRule.IRREGULAR,
    hundred="शंभर",
    scales=((10_000_000, "कोटी"), (100_000, "लाख"), (1_000, "हजार")),
    point="दशांश",
    units={"%": ("टक्के", "टक्के"), "gb": ("गिगाबाइट", "गिगाबाइट")},
)

BENGALI = LanguagePack(
    code="bn",
    label="Bengali",
    endonym="বাংলা",
    negations=("না", "নেই", "কখনো না", "ছাড়া", "নয়"),
    intensifiers=("খুব", "অত্যন্ত", "সম্পূর্ণ", "ভীষণ"),
    hedges=("হয়তো", "সম্ভবত", "মনে হয়"),
    clause_breaks=("কিন্তু", "তবে", "যদিও", "তথাপি"),
    cues={
        Emotion.EXCITED: ("অসাধারণ", "চমৎকার", "দুর্দান্ত"),
        Emotion.HAPPY: ("ভালো", "ধন্যবাদ", "সফল", "খুশি", "ঠিক হয়েছে"),
        Emotion.CONFIDENT: ("নিশ্চিত", "নিশ্চিতভাবে", "যাচাই"),
        Emotion.CURIOUS: ("আকর্ষণীয়", "কৌতূহল"),
        Emotion.CALM: ("শান্ত", "স্থিতিশীল"),
        Emotion.CONCERNED: ("সতর্ক", "ঝুঁকি", "বিপদ", "সাবধান"),
        Emotion.SERIOUS: ("গুরুতর", "জরুরি", "নিরাপত্তা"),
        Emotion.SAD: ("দুঃখিত", "ব্যর্থ", "ত্রুটি", "ভাঙা", "দুর্ভাগ্যবশত"),
    },
    ones=("শূন্য", "এক", "দুই", "তিন", "চার", "পাঁচ", "ছয়", "সাত", "আট", "নয়",
          "দশ", "এগারো", "বারো", "তেরো", "চোদ্দ", "পনেরো", "ষোলো", "সতেরো", "আঠারো", "উনিশ",
          "বিশ"),
    tens=("", "", "বিশ", "ত্রিশ", "চল্লিশ", "পঞ্চাশ", "ষাট", "সত্তর", "আশি", "নব্বই"),
    tens_rule=TensRule.IRREGULAR,
    hundred="শত",
    scales=((10_000_000, "কোটি"), (100_000, "লাখ"), (1_000, "হাজার")),
    point="দশমিক",
    units={"%": ("শতাংশ", "শতাংশ"), "gb": ("গিগাবাইট", "গিগাবাইট")},
)

GUJARATI = LanguagePack(
    code="gu",
    label="Gujarati",
    endonym="ગુજરાતી",
    negations=("નથી", "ના", "કદી નહીં", "વગર"),
    intensifiers=("ખૂબ", "અત્યંત", "સંપૂર્ણ"),
    hedges=("કદાચ", "સંભવતઃ", "લાગે છે"),
    clause_breaks=("પણ", "પરંતુ", "તેમ છતાં"),
    cues={
        Emotion.EXCITED: ("અદ્ભુત", "શાનદાર", "ઉત્તમ"),
        Emotion.HAPPY: ("સારું", "આભાર", "સફળ", "ખુશ", "ઠીક થયું"),
        Emotion.CONFIDENT: ("ચોક્કસ", "પુષ્ટિ", "ખાતરી"),
        Emotion.CURIOUS: ("રસપ્રદ", "જિજ્ઞાસુ"),
        Emotion.CALM: ("શાંત", "સ્થિર"),
        Emotion.CONCERNED: ("સાવધાન", "જોખમ", "ભય", "ચેતવણી"),
        Emotion.SERIOUS: ("ગંભીર", "તાત્કાલિક", "સુરક્ષા"),
        Emotion.SAD: ("માફ કરશો", "નિષ્ફળ", "ભૂલ", "તૂટેલું", "કમનસીબે"),
    },
    ones=("શૂન્ય", "એક", "બે", "ત્રણ", "ચાર", "પાંચ", "છ", "સાત", "આઠ", "નવ",
          "દસ", "અગિયાર", "બાર", "તેર", "ચૌદ", "પંદર", "સોળ", "સત્તર", "અઢાર", "ઓગણીસ",
          "વીસ"),
    tens=("", "", "વીસ", "ત્રીસ", "ચાળીસ", "પચાસ", "સાઠ", "સિત્તેર", "એંસી", "નેવું"),
    tens_rule=TensRule.IRREGULAR,
    hundred="સો",
    scales=((10_000_000, "કરોડ"), (100_000, "લાખ"), (1_000, "હજાર")),
    point="દશાંશ",
    units={"%": ("ટકા", "ટકા"), "gb": ("ગીગાબાઇટ", "ગીગાબાઇટ")},
)

PUNJABI = LanguagePack(
    code="pa",
    label="Punjabi",
    endonym="ਪੰਜਾਬੀ",
    negations=("ਨਹੀਂ", "ਨਾ", "ਕਦੇ ਨਹੀਂ", "ਬਿਨਾਂ"),
    intensifiers=("ਬਹੁਤ", "ਅਤਿਅੰਤ", "ਪੂਰੀ ਤਰ੍ਹਾਂ"),
    hedges=("ਸ਼ਾਇਦ", "ਸੰਭਵ", "ਲੱਗਦਾ"),
    clause_breaks=("ਪਰ", "ਹਾਲਾਂਕਿ", "ਫਿਰ ਵੀ"),
    cues={
        Emotion.EXCITED: ("ਸ਼ਾਨਦਾਰ", "ਬਹੁਤ ਵਧੀਆ", "ਅਦਭੁਤ"),
        Emotion.HAPPY: ("ਚੰਗਾ", "ਧੰਨਵਾਦ", "ਸਫਲ", "ਖੁਸ਼", "ਠੀਕ ਹੋ ਗਿਆ"),
        Emotion.CONFIDENT: ("ਯਕੀਨੀ", "ਪੁਸ਼ਟੀ", "ਪੱਕਾ"),
        Emotion.CURIOUS: ("ਦਿਲਚਸਪ", "ਉਤਸੁਕ"),
        Emotion.CALM: ("ਸ਼ਾਂਤ", "ਸਥਿਰ"),
        Emotion.CONCERNED: ("ਸਾਵਧਾਨ", "ਜੋਖਮ", "ਖਤਰਾ", "ਚੇਤਾਵਨੀ"),
        Emotion.SERIOUS: ("ਗੰਭੀਰ", "ਜ਼ਰੂਰੀ", "ਸੁਰੱਖਿਆ"),
        Emotion.SAD: ("ਮਾਫ਼", "ਅਸਫਲ", "ਗਲਤੀ", "ਟੁੱਟਿਆ", "ਬਦਕਿਸਮਤੀ"),
    },
    ones=("ਜ਼ੀਰੋ", "ਇੱਕ", "ਦੋ", "ਤਿੰਨ", "ਚਾਰ", "ਪੰਜ", "ਛੇ", "ਸੱਤ", "ਅੱਠ", "ਨੌਂ",
          "ਦਸ", "ਗਿਆਰਾਂ", "ਬਾਰਾਂ", "ਤੇਰਾਂ", "ਚੌਦਾਂ", "ਪੰਦਰਾਂ", "ਸੋਲਾਂ", "ਸਤਾਰਾਂ", "ਅਠਾਰਾਂ", "ਉੱਨੀ",
          "ਵੀਹ"),
    tens=("", "", "ਵੀਹ", "ਤੀਹ", "ਚਾਲੀ", "ਪੰਜਾਹ", "ਸੱਠ", "ਸੱਤਰ", "ਅੱਸੀ", "ਨੱਬੇ"),
    tens_rule=TensRule.IRREGULAR,
    hundred="ਸੌ",
    scales=((10_000_000, "ਕਰੋੜ"), (100_000, "ਲੱਖ"), (1_000, "ਹਜ਼ਾਰ")),
    point="ਦਸ਼ਮਲਵ",
    units={"%": ("ਪ੍ਰਤੀਸ਼ਤ", "ਪ੍ਰਤੀਸ਼ਤ"), "gb": ("ਗੀਗਾਬਾਈਟ", "ਗੀਗਾਬਾਈਟ")},
)

TAMIL = LanguagePack(
    code="ta",
    label="Tamil",
    endonym="தமிழ்",
    negations=("இல்லை", "இல்ல", "ஒருபோதும்", "இன்றி", "அல்ல"),
    intensifiers=("மிகவும்", "அதிக", "முற்றிலும்", "ரொம்ப"),
    hedges=("ஒருவேளை", "சாத்தியம்", "தோன்றுகிறது"),
    clause_breaks=("ஆனால்", "எனினும்", "இருப்பினும்"),
    cues={
        Emotion.EXCITED: ("அற்புதம்", "அருமை", "சிறப்பு"),
        Emotion.HAPPY: ("நல்ல", "நன்றி", "வெற்றி", "மகிழ்ச்சி", "சரியானது"),
        Emotion.CONFIDENT: ("நிச்சயம்", "உறுதி", "சரிபார்க்கப்பட்டது"),
        Emotion.CURIOUS: ("சுவாரஸ்யம்", "ஆர்வம்"),
        Emotion.CALM: ("அமைதி", "நிலையான"),
        Emotion.CONCERNED: ("கவனம்", "ஆபத்து", "எச்சரிக்கை"),
        Emotion.SERIOUS: ("தீவிர", "அவசர", "பாதுகாப்பு"),
        Emotion.SAD: ("மன்னிக்கவும்", "தோல்வி", "பிழை", "உடைந்த", "துரதிர்ஷ்டவசமாக"),
    },
    ones=("பூஜ்யம்", "ஒன்று", "இரண்டு", "மூன்று", "நான்கு", "ஐந்து", "ஆறு", "ஏழு", "எட்டு", "ஒன்பது",
          "பத்து", "பதினொன்று", "பன்னிரண்டு", "பதிமூன்று", "பதினான்கு", "பதினைந்து",
          "பதினாறு", "பதினேழு", "பதினெட்டு", "பத்தொன்பது",
          "இருபது"),
    tens=("", "", "இருபது", "முப்பது", "நாற்பது", "ஐம்பது", "அறுபது", "எழுபது", "எண்பது", "தொண்ணூறு"),
    tens_rule=TensRule.IRREGULAR,
    hundred="நூறு",
    scales=((10_000_000, "கோடி"), (100_000, "லட்சம்"), (1_000, "ஆயிரம்")),
    point="புள்ளி",
    units={"%": ("சதவீதம்", "சதவீதம்"), "gb": ("ஜிகாபைட்", "ஜிகாபைட்")},
)

TELUGU = LanguagePack(
    code="te",
    label="Telugu",
    endonym="తెలుగు",
    negations=("లేదు", "కాదు", "ఎప్పుడూ లేదు", "లేకుండా"),
    intensifiers=("చాలా", "అత్యంత", "పూర్తిగా"),
    hedges=("బహుశా", "సాధ్యం", "అనిపిస్తుంది"),
    clause_breaks=("కానీ", "అయితే", "అయినప్పటికీ"),
    cues={
        Emotion.EXCITED: ("అద్భుతం", "అమోఘం", "గొప్ప"),
        Emotion.HAPPY: ("మంచి", "ధన్యవాదాలు", "విజయం", "సంతోషం", "సరిచేయబడింది"),
        Emotion.CONFIDENT: ("ఖచ్చితంగా", "నిర్ధారించబడింది", "ధృవీకరించబడింది"),
        Emotion.CURIOUS: ("ఆసక్తికరం", "కుతూహలం"),
        Emotion.CALM: ("ప్రశాంతం", "స్థిరం"),
        Emotion.CONCERNED: ("జాగ్రత్త", "ప్రమాదం", "హెచ్చరిక"),
        Emotion.SERIOUS: ("తీవ్రమైన", "అత్యవసర", "భద్రత"),
        Emotion.SAD: ("క్షమించండి", "విఫలం", "లోపం", "విరిగిన", "దురదృష్టవశాత్తు"),
    },
    ones=("సున్నా", "ఒకటి", "రెండు", "మూడు", "నాలుగు", "ఐదు", "ఆరు", "ఏడు", "ఎనిమిది", "తొమ్మిది",
          "పది", "పదకొండు", "పన్నెండు", "పదమూడు", "పద్నాలుగు", "పదిహేను",
          "పదహారు", "పదిహేడు", "పద్దెనిమిది", "పంతొమ్మిది",
          "ఇరవై"),
    tens=("", "", "ఇరవై", "ముప్పై", "నలభై", "యాభై", "అరవై", "డెబ్బై", "ఎనభై", "తొంభై"),
    tens_rule=TensRule.IRREGULAR,
    hundred="వంద",
    scales=((10_000_000, "కోటి"), (100_000, "లక్ష"), (1_000, "వేయి")),
    point="దశాంశ",
    units={"%": ("శాతం", "శాతం"), "gb": ("గిగాబైట్", "గిగాబైట్")},
)

KANNADA = LanguagePack(
    code="kn",
    label="Kannada",
    endonym="ಕನ್ನಡ",
    negations=("ಇಲ್ಲ", "ಅಲ್ಲ", "ಎಂದಿಗೂ ಇಲ್ಲ", "ಇಲ್ಲದೆ"),
    intensifiers=("ತುಂಬಾ", "ಅತ್ಯಂತ", "ಸಂಪೂರ್ಣವಾಗಿ"),
    hedges=("ಬಹುಶಃ", "ಸಾಧ್ಯ", "ತೋರುತ್ತದೆ"),
    clause_breaks=("ಆದರೆ", "ಆದಾಗ್ಯೂ", "ಹಾಗಿದ್ದರೂ"),
    cues={
        Emotion.EXCITED: ("ಅದ್ಭುತ", "ಅತ್ಯುತ್ತಮ", "ಅಮೋಘ"),
        Emotion.HAPPY: ("ಒಳ್ಳೆಯದು", "ಧನ್ಯವಾದ", "ಯಶಸ್ವಿ", "ಸಂತೋಷ", "ಸರಿಪಡಿಸಲಾಗಿದೆ"),
        Emotion.CONFIDENT: ("ಖಚಿತ", "ದೃಢಪಡಿಸಲಾಗಿದೆ", "ಪರಿಶೀಲಿಸಲಾಗಿದೆ"),
        Emotion.CURIOUS: ("ಆಸಕ್ತಿದಾಯಕ", "ಕುತೂಹಲ"),
        Emotion.CALM: ("ಶಾಂತ", "ಸ್ಥಿರ"),
        Emotion.CONCERNED: ("ಎಚ್ಚರಿಕೆ", "ಅಪಾಯ", "ಅಪಾಯಕಾರಿ"),
        Emotion.SERIOUS: ("ಗಂಭೀರ", "ತುರ್ತು", "ಭದ್ರತೆ"),
        Emotion.SAD: ("ಕ್ಷಮಿಸಿ", "ವಿಫಲ", "ದೋಷ", "ಮುರಿದ", "ದುರದೃಷ್ಟವಶಾತ್"),
    },
    ones=("ಸೊನ್ನೆ", "ಒಂದು", "ಎರಡು", "ಮೂರು", "ನಾಲ್ಕು", "ಐದು", "ಆರು", "ಏಳು", "ಎಂಟು", "ಒಂಬತ್ತು",
          "ಹತ್ತು", "ಹನ್ನೊಂದು", "ಹನ್ನೆರಡು", "ಹದಿಮೂರು", "ಹದಿನಾಲ್ಕು", "ಹದಿನೈದು",
          "ಹದಿನಾರು", "ಹದಿನೇಳು", "ಹದಿನೆಂಟು", "ಹತ್ತೊಂಬತ್ತು",
          "ಇಪ್ಪತ್ತು"),
    tens=("", "", "ಇಪ್ಪತ್ತು", "ಮೂವತ್ತು", "ನಲವತ್ತು", "ಐವತ್ತು", "ಅರವತ್ತು", "ಎಪ್ಪತ್ತು", "ಎಂಬತ್ತು", "ತೊಂಬತ್ತು"),
    tens_rule=TensRule.IRREGULAR,
    hundred="ನೂರು",
    scales=((10_000_000, "ಕೋಟಿ"), (100_000, "ಲಕ್ಷ"), (1_000, "ಸಾವಿರ")),
    point="ದಶಮಾಂಶ",
    units={"%": ("ಶೇಕಡಾ", "ಶೇಕಡಾ"), "gb": ("ಗಿಗಾಬೈಟ್", "ಗಿಗಾಬೈಟ್")},
)

MALAYALAM = LanguagePack(
    code="ml",
    label="Malayalam",
    endonym="മലയാളം",
    negations=("ഇല്ല", "അല്ല", "ഒരിക്കലും ഇല്ല", "ഇല്ലാതെ"),
    intensifiers=("വളരെ", "അത്യന്തം", "പൂർണ്ണമായും"),
    hedges=("ഒരുപക്ഷേ", "സാധ്യത", "തോന്നുന്നു"),
    clause_breaks=("പക്ഷേ", "എന്നാൽ", "എങ്കിലും"),
    cues={
        Emotion.EXCITED: ("അതിശയകരം", "മികച്ചത്", "അത്ഭുതം"),
        Emotion.HAPPY: ("നല്ലത്", "നന്ദി", "വിജയം", "സന്തോഷം", "ശരിയാക്കി"),
        Emotion.CONFIDENT: ("തീർച്ചയായും", "സ്ഥിരീകരിച്ചു", "പരിശോധിച്ചു"),
        Emotion.CURIOUS: ("രസകരം", "ജിജ്ഞാസ"),
        Emotion.CALM: ("ശാന്തം", "സ്ഥിരം"),
        Emotion.CONCERNED: ("ജാഗ്രത", "അപകടം", "മുന്നറിയിപ്പ്"),
        Emotion.SERIOUS: ("ഗുരുതരം", "അടിയന്തിരം", "സുരക്ഷ"),
        Emotion.SAD: ("ക്ഷമിക്കണം", "പരാജയം", "പിശക്", "തകർന്ന", "നിർഭാഗ്യവശാൽ"),
    },
    ones=("പൂജ്യം", "ഒന്ന്", "രണ്ട്", "മൂന്ന്", "നാല്", "അഞ്ച്", "ആറ്", "ഏഴ്", "എട്ട്", "ഒൻപത്",
          "പത്ത്", "പതിനൊന്ന്", "പന്ത്രണ്ട്", "പതിമൂന്ന്", "പതിനാല്", "പതിനഞ്ച്",
          "പതിനാറ്", "പതിനേഴ്", "പതിനെട്ട്", "പത്തൊൻപത്",
          "ഇരുപത്"),
    tens=("", "", "ഇരുപത്", "മുപ്പത്", "നാൽപ്പത്", "അൻപത്", "അറുപത്", "എഴുപത്", "എൺപത്", "തൊണ്ണൂറ്"),
    tens_rule=TensRule.IRREGULAR,
    hundred="നൂറ്",
    scales=((10_000_000, "കോടി"), (100_000, "ലക്ഷം"), (1_000, "ആയിരം")),
    point="ദശാംശം",
    units={"%": ("ശതമാനം", "ശതമാനം"), "gb": ("ജിഗാബൈറ്റ്", "ജിഗാബൈറ്റ്")},
)

SINHALA = LanguagePack(
    code="si",
    label="Sinhala",
    endonym="සිංහල",
    negations=("නැහැ", "නොවේ", "කවදාවත් නැහැ", "නැතිව"),
    intensifiers=("ඉතා", "අතිශය", "සම්පූර්ණයෙන්"),
    hedges=("සමහරවිට", "බොහෝවිට", "පෙනේ"),
    clause_breaks=("නමුත්", "එහෙත්", "කෙසේවෙතත්"),
    cues={
        Emotion.EXCITED: ("පුදුම", "විශිෂ්ට", "අපූරු"),
        Emotion.HAPPY: ("හොඳයි", "ස්තූතියි", "සාර්ථක", "සතුටු", "හදලා"),
        Emotion.CONFIDENT: ("නිසැක", "තහවුරු", "සත්‍යාපනය"),
        Emotion.CURIOUS: ("සිත්ගන්නා", "කුතුහල"),
        Emotion.CALM: ("සන්සුන්", "ස්ථාවර"),
        Emotion.CONCERNED: ("පරෙස්සම්", "අවදානම", "අනතුර"),
        Emotion.SERIOUS: ("බරපතල", "හදිසි", "ආරක්ෂාව"),
        Emotion.SAD: ("සමාවන්න", "අසාර්ථක", "දෝෂය", "කැඩුණු", "අවාසනාවකට"),
    },
    ones=("බිංදුව", "එක", "දෙක", "තුන", "හතර", "පහ", "හය", "හත", "අට", "නවය",
          "දහය", "එකොළහ", "දොළහ", "දහතුන", "දාහතර", "පහළොව",
          "දහසය", "දහහත", "දහඅට", "දහනවය",
          "විස්ස"),
    tens=("", "", "විස්ස", "තිහ", "හතළිහ", "පනහ", "හැට", "හැත්තෑව", "අසූව", "අනූව"),
    tens_rule=TensRule.IRREGULAR,
    hundred="සියය",
    scales=((100_000, "ලක්ෂ"), (1_000, "දහස")),
    point="දශම",
    units={"%": ("සියයට", "සියයට")},
)

URDU = LanguagePack(
    code="ur",
    label="Urdu",
    endonym="اردو",
    negations=("نہیں", "نہ", "کبھی نہیں", "بغیر"),
    intensifiers=("بہت", "انتہائی", "مکمل طور پر"),
    hedges=("شاید", "ممکن", "لگتا ہے"),
    clause_breaks=("لیکن", "مگر", "تاہم", "پھر بھی"),
    cues={
        Emotion.EXCITED: ("حیرت انگیز", "شاندار", "بہترین"),
        Emotion.HAPPY: ("اچھا", "شکریہ", "کامیاب", "خوش", "ٹھیک ہو گیا"),
        Emotion.CONFIDENT: ("یقینی", "تصدیق", "پکا"),
        Emotion.CURIOUS: ("دلچسپ", "تجسس"),
        Emotion.CALM: ("پرسکون", "مستحکم"),
        Emotion.CONCERNED: ("احتیاط", "خطرہ", "انتباہ"),
        Emotion.SERIOUS: ("سنگین", "فوری", "سیکیورٹی"),
        Emotion.SAD: ("معذرت", "ناکام", "خرابی", "ٹوٹا", "بدقسمتی سے"),
    },
    ones=("صفر", "ایک", "دو", "تین", "چار", "پانچ", "چھ", "سات", "آٹھ", "نو",
          "دس", "گیارہ", "بارہ", "تیرہ", "چودہ", "پندرہ", "سولہ", "سترہ", "اٹھارہ", "انیس",
          "بیس"),
    tens=("", "", "بیس", "تیس", "چالیس", "پچاس", "ساٹھ", "ستر", "اسی", "نوے"),
    tens_rule=TensRule.IRREGULAR,
    hundred="سو",
    scales=((10_000_000, "کروڑ"), (100_000, "لاکھ"), (1_000, "ہزار")),
    point="اعشاریہ",
    units={"%": ("فیصد", "فیصد"), "gb": ("گیگا بائٹ", "گیگا بائٹ")},
)

ARABIC = LanguagePack(
    code="ar",
    label="Arabic",
    endonym="العربية",
    negations=("لا", "ليس", "لم", "لن", "ما", "أبدا", "بدون", "غير"),
    intensifiers=("جدا", "حقا", "للغاية", "تماما", "بشدة"),
    hedges=("ربما", "قد", "يبدو", "محتمل"),
    clause_breaks=("لكن", "لكن", "رغم", "مع ذلك"),
    cues={
        Emotion.EXCITED: ("رائع", "مذهل", "ممتاز", "مدهش"),
        Emotion.HAPPY: ("جيد", "شكرا", "نجاح", "سعيد", "تم الإصلاح", "يعمل"),
        Emotion.CONFIDENT: ("بالتأكيد", "مؤكد", "تم التحقق", "طبعا"),
        Emotion.CURIOUS: ("مثير للاهتمام", "فضول"),
        Emotion.CALM: ("هادئ", "مستقر"),
        Emotion.CONCERNED: ("تحذير", "خطر", "احذر", "مخاطرة"),
        Emotion.SERIOUS: ("حرج", "عاجل", "خطير", "أمان", "ثغرة"),
        Emotion.SAD: ("آسف", "للأسف", "فشل", "خطأ", "معطل", "مفقود"),
    },
    ones=("صفر", "واحد", "اثنان", "ثلاثة", "أربعة", "خمسة", "ستة", "سبعة", "ثمانية", "تسعة",
          "عشرة", "أحد عشر", "اثنا عشر", "ثلاثة عشر", "أربعة عشر", "خمسة عشر",
          "ستة عشر", "سبعة عشر", "ثمانية عشر", "تسعة عشر"),
    tens=("", "", "عشرون", "ثلاثون", "أربعون", "خمسون", "ستون", "سبعون", "ثمانون", "تسعون"),
    # Arabic says the ones first: 87 is "سبعة وثمانون" (seven and eighty).
    tens_rule=TensRule.ONES_FIRST,
    compound=" و",
    hundred="مائة",
    hundreds=("", "مائة", "مائتان", "ثلاثمائة", "أربعمائة", "خمسمائة",
              "ستمائة", "سبعمائة", "ثمانمائة", "تسعمائة"),
    scales=((1_000_000, "مليون"), (1_000, "ألف")),
    point="فاصلة",
    units={"%": ("بالمئة", "بالمئة"), "ms": ("ميلي ثانية", "ميلي ثانية"),
           "gb": ("جيجابايت", "جيجابايت"), "mb": ("ميجابايت", "ميجابايت")},
)

HEBREW = LanguagePack(
    code="he",
    label="Hebrew",
    endonym="עברית",
    negations=("לא", "אין", "אף פעם", "בלי", "ללא"),
    intensifiers=("מאוד", "באמת", "לגמרי", "ממש", "לחלוטין"),
    hedges=("אולי", "ייתכן", "נראה", "כנראה"),
    clause_breaks=("אבל", "אך", "למרות", "עם זאת"),
    cues={
        Emotion.EXCITED: ("מדהים", "מצוין", "נהדר", "פנטסטי"),
        Emotion.HAPPY: ("טוב", "תודה", "הצלחה", "שמח", "תוקן", "עובד"),
        Emotion.CONFIDENT: ("בהחלט", "מאושר", "מאומת", "בטח"),
        Emotion.CURIOUS: ("מעניין", "סקרן"),
        Emotion.CALM: ("רגוע", "יציב"),
        Emotion.CONCERNED: ("אזהרה", "זהירות", "סיכון", "סכנה"),
        Emotion.SERIOUS: ("קריטי", "דחוף", "חמור", "אבטחה", "פגיעות"),
        Emotion.SAD: ("סליחה", "לצערי", "נכשל", "שגיאה", "שבור", "אבד"),
    },
    ones=("אפס", "אחת", "שתיים", "שלוש", "ארבע", "חמש", "שש", "שבע", "שמונה", "תשע",
          "עשר", "אחת עשרה", "שתים עשרה", "שלוש עשרה", "ארבע עשרה", "חמש עשרה",
          "שש עשרה", "שבע עשרה", "שמונה עשרה", "תשע עשרה"),
    tens=("", "", "עשרים", "שלושים", "ארבעים", "חמישים", "שישים", "שבעים", "שמונים", "תשעים"),
    tens_rule=TensRule.TENS_FIRST,
    compound=" ו",
    hundred="מאה",
    hundreds=("", "מאה", "מאתיים", "שלוש מאות", "ארבע מאות", "חמש מאות",
              "שש מאות", "שבע מאות", "שמונה מאות", "תשע מאות"),
    scales=((1_000_000, "מיליון"), (1_000, "אלף")),
    point="נקודה",
    units={"%": ("אחוז", "אחוזים"), "gb": ("גיגה בייט", "גיגה בייט")},
)

PERSIAN = LanguagePack(
    code="fa",
    label="Persian",
    endonym="فارسی",
    negations=("نه", "نیست", "هرگز", "بدون", "نمی"),
    intensifiers=("خیلی", "بسیار", "کاملا", "شدیدا"),
    hedges=("شاید", "احتمالا", "به نظر می‌رسد"),
    clause_breaks=("اما", "ولی", "هرچند", "با این حال"),
    cues={
        Emotion.EXCITED: ("عالی", "فوق‌العاده", "شگفت‌انگیز"),
        Emotion.HAPPY: ("خوب", "ممنون", "موفق", "خوشحال", "درست شد"),
        Emotion.CONFIDENT: ("قطعا", "تایید شد", "مطمئن"),
        Emotion.CURIOUS: ("جالب", "کنجکاو"),
        Emotion.CALM: ("آرام", "پایدار"),
        Emotion.CONCERNED: ("هشدار", "خطر", "احتیاط", "ریسک"),
        Emotion.SERIOUS: ("بحرانی", "فوری", "جدی", "امنیت"),
        Emotion.SAD: ("متاسفم", "متاسفانه", "ناموفق", "خطا", "خراب", "گم"),
    },
    ones=("صفر", "یک", "دو", "سه", "چهار", "پنج", "شش", "هفت", "هشت", "نه",
          "ده", "یازده", "دوازده", "سیزده", "چهارده", "پانزده", "شانزده", "هفده", "هجده", "نوزده"),
    tens=("", "", "بیست", "سی", "چهل", "پنجاه", "شصت", "هفتاد", "هشتاد", "نود"),
    tens_rule=TensRule.TENS_FIRST,
    compound=" و ",
    hundred="صد",
    hundreds=("", "صد", "دویست", "سیصد", "چهارصد", "پانصد",
              "ششصد", "هفتصد", "هشتصد", "نهصد"),
    join=" ",
    # Persian links every group with و, but only between groups:
    # "دو میلیون و پانصد هزار", not "دو و میلیون".
    group_join=" و ",
    scales=((1_000_000, "میلیون"), (1_000, "هزار")),
    point="ممیز",
    units={"%": ("درصد", "درصد"), "gb": ("گیگابایت", "گیگابایت")},
)

JAPANESE = LanguagePack(
    code="ja",
    label="Japanese",
    endonym="日本語",
    negations=("ない", "ません", "じゃない", "なし", "ぬ"),
    intensifiers=("とても", "非常に", "すごく", "本当に", "完全に"),
    hedges=("たぶん", "おそらく", "かもしれない", "ようだ"),
    clause_breaks=("でも", "しかし", "けれど", "だが"),
    cues={
        Emotion.EXCITED: ("素晴らしい", "すごい", "最高", "見事"),
        Emotion.HAPPY: ("ありがとう", "成功", "嬉しい", "直った", "良い", "動いた"),
        Emotion.CONFIDENT: ("確実", "確認", "もちろん"),
        Emotion.CURIOUS: ("面白い", "興味深い"),
        Emotion.CALM: ("安定", "静か", "落ち着"),
        Emotion.CONCERNED: ("注意", "危険", "警告", "リスク"),
        Emotion.SERIOUS: ("重大", "緊急", "深刻", "セキュリティ", "脆弱性"),
        Emotion.SAD: ("すみません", "申し訳", "失敗", "エラー", "残念", "壊れ"),
    },
    # Japanese counters change the reading of a number depending on what is
    # counted -- 一本 is "ippon", 一人 is "hitori", 一つ is "hitotsu". A flat
    # table would be wrong more often than right, so digits are left alone.
    units={"%": ("パーセント", "パーセント"), "ms": ("ミリ秒", "ミリ秒"),
           "gb": ("ギガバイト", "ギガバイト"), "mb": ("メガバイト", "メガバイト")},
)

CHINESE = LanguagePack(
    code="zh",
    label="Chinese",
    endonym="中文",
    negations=("不", "没", "没有", "无", "非", "未", "别"),
    intensifiers=("非常", "很", "特别", "极其", "完全", "十分"),
    hedges=("可能", "也许", "大概", "似乎", "或许"),
    clause_breaks=("但是", "但", "然而", "虽然", "不过"),
    cues={
        Emotion.EXCITED: ("太棒了", "了不起", "精彩", "极好"),
        Emotion.HAPPY: ("好", "谢谢", "成功", "高兴", "修复", "正常"),
        Emotion.CONFIDENT: ("确定", "确认", "已验证", "当然"),
        Emotion.CURIOUS: ("有趣", "好奇"),
        Emotion.CALM: ("稳定", "平静"),
        Emotion.CONCERNED: ("注意", "小心", "危险", "警告", "风险"),
        Emotion.SERIOUS: ("严重", "紧急", "关键", "安全", "漏洞"),
        Emotion.SAD: ("抱歉", "对不起", "失败", "错误", "损坏", "遗憾"),
    },
    ones=("零", "一", "二", "三", "四", "五", "六", "七", "八", "九"),
    tens=("", "十", "二十", "三十", "四十", "五十", "六十", "七十", "八十", "九十"),
    tens_rule=TensRule.DECIMAL,
    compound="",
    hundred="百",
    hundred_needs_one=True,
    join="",
    scales=((100_000_000, "亿"), (10_000, "万"), (1_000, "千")),
    point="点",
    units={"%": ("百分之", "百分之"), "ms": ("毫秒", "毫秒"),
           "gb": ("吉字节", "吉字节"), "mb": ("兆字节", "兆字节")},
    units_before=("%",),
)

KOREAN = LanguagePack(
    code="ko",
    label="Korean",
    endonym="한국어",
    negations=("안", "없", "못", "아니", "없이"),
    intensifiers=("매우", "정말", "너무", "완전히", "굉장히"),
    hedges=("아마", "어쩌면", "같습니다", "듯"),
    clause_breaks=("그러나", "하지만", "그런데", "비록"),
    cues={
        Emotion.EXCITED: ("훌륭", "대단", "최고", "멋지"),
        Emotion.HAPPY: ("좋", "감사", "성공", "기쁘", "수정", "작동"),
        Emotion.CONFIDENT: ("확실", "확인", "검증", "물론"),
        Emotion.CURIOUS: ("흥미", "궁금"),
        Emotion.CALM: ("안정", "차분"),
        Emotion.CONCERNED: ("주의", "위험", "경고"),
        Emotion.SERIOUS: ("심각", "긴급", "치명", "보안", "취약점"),
        Emotion.SAD: ("죄송", "실패", "오류", "고장", "안타깝"),
    },
    # Korean has two number systems -- native (하나, 둘) and Sino-Korean (일,
    # 이) -- and which one applies depends on the counter that follows. Same
    # reason as Japanese: a table cannot choose correctly.
    units={"%": ("퍼센트", "퍼센트"), "ms": ("밀리초", "밀리초"),
           "gb": ("기가바이트", "기가바이트"), "mb": ("메가바이트", "메가바이트")},
)

THAI = LanguagePack(
    code="th",
    label="Thai",
    endonym="ไทย",
    negations=("ไม่", "ไม่ได้", "ไม่เคย", "ปราศจาก", "ไร้"),
    intensifiers=("มาก", "อย่างยิ่ง", "สุดๆ", "เต็มที่"),
    hedges=("อาจจะ", "บางที", "ดูเหมือน", "คงจะ"),
    clause_breaks=("แต่", "อย่างไรก็ตาม", "ถึงแม้"),
    cues={
        Emotion.EXCITED: ("ยอดเยี่ยม", "เยี่ยม", "สุดยอด"),
        Emotion.HAPPY: ("ดี", "ขอบคุณ", "สำเร็จ", "ยินดี", "แก้ไขแล้ว"),
        Emotion.CONFIDENT: ("แน่นอน", "ยืนยัน", "ตรวจสอบแล้ว"),
        Emotion.CURIOUS: ("น่าสนใจ", "สงสัย"),
        Emotion.CALM: ("สงบ", "เสถียร"),
        Emotion.CONCERNED: ("ระวัง", "อันตราย", "เตือน", "ความเสี่ยง"),
        Emotion.SERIOUS: ("วิกฤต", "ด่วน", "ร้ายแรง", "ความปลอดภัย"),
        Emotion.SAD: ("ขอโทษ", "ล้มเหลว", "ข้อผิดพลาด", "เสีย", "น่าเสียดาย"),
    },
    ones=("ศูนย์", "หนึ่ง", "สอง", "สาม", "สี่", "ห้า", "หก", "เจ็ด", "แปด", "เก้า",
          "สิบ", "สิบเอ็ด", "สิบสอง", "สิบสาม", "สิบสี่", "สิบห้า",
          "สิบหก", "สิบเจ็ด", "สิบแปด", "สิบเก้า"),
    tens=("", "", "ยี่สิบ", "สามสิบ", "สี่สิบ", "ห้าสิบ", "หกสิบ", "เจ็ดสิบ", "แปดสิบ", "เก้าสิบ"),
    tens_rule=TensRule.TENS_FIRST,
    compound="",
    hundred="ร้อย",
    hundred_needs_one=True,
    join="",
    scales=((1_000_000, "ล้าน"), (100_000, "แสน"), (10_000, "หมื่น"), (1_000, "พัน")),
    point="จุด",
    units={"%": ("เปอร์เซ็นต์", "เปอร์เซ็นต์"), "gb": ("กิกะไบต์", "กิกะไบต์")},
)

VIETNAMESE = LanguagePack(
    code="vi",
    label="Vietnamese",
    endonym="Tiếng Việt",
    negations=("không", "chưa", "chẳng", "đừng", "không bao giờ"),
    intensifiers=("rất", "cực kỳ", "hoàn toàn", "vô cùng", "quá"),
    hedges=("có lẽ", "có thể", "dường như", "chắc"),
    clause_breaks=("nhưng", "tuy nhiên", "mặc dù", "song"),
    cues={
        Emotion.EXCITED: ("tuyệt vời", "xuất sắc", "tuyệt", "hoàn hảo"),
        Emotion.HAPPY: ("tốt", "cảm ơn", "thành công", "vui", "đã sửa", "hoạt động"),
        Emotion.CONFIDENT: ("chắc chắn", "đã xác nhận", "đã kiểm tra"),
        Emotion.CURIOUS: ("thú vị", "tò mò"),
        Emotion.CALM: ("bình tĩnh", "ổn định"),
        Emotion.CONCERNED: ("cảnh báo", "nguy hiểm", "rủi ro", "cẩn thận"),
        Emotion.SERIOUS: ("nghiêm trọng", "khẩn cấp", "bảo mật", "lỗ hổng"),
        Emotion.SAD: ("xin lỗi", "tiếc", "thất bại", "lỗi", "hỏng", "mất"),
    },
    ones=("không", "một", "hai", "ba", "bốn", "năm", "sáu", "bảy", "tám", "chín",
          "mười", "mười một", "mười hai", "mười ba", "mười bốn", "mười lăm",
          "mười sáu", "mười bảy", "mười tám", "mười chín"),
    tens=("", "", "hai mươi", "ba mươi", "bốn mươi", "năm mươi", "sáu mươi",
          "bảy mươi", "tám mươi", "chín mươi"),
    tens_rule=TensRule.TENS_FIRST,
    hundred="trăm",
    hundred_needs_one=True,
    scales=((1_000_000, "triệu"), (1_000, "nghìn")),
    point="phẩy",
    units={"%": ("phần trăm", "phần trăm"), "gb": ("gigabyte", "gigabyte")},
)

INDONESIAN = LanguagePack(
    code="id",
    label="Indonesian",
    endonym="Bahasa Indonesia",
    negations=("tidak", "bukan", "tanpa", "jangan", "belum", "tak"),
    intensifiers=("sangat", "sekali", "amat", "benar-benar", "sepenuhnya"),
    hedges=("mungkin", "sepertinya", "kira-kira", "barangkali"),
    clause_breaks=("tetapi", "tapi", "namun", "meskipun"),
    cues={
        Emotion.EXCITED: ("luar biasa", "hebat", "sempurna", "keren"),
        Emotion.HAPPY: ("bagus", "baik", "terima kasih", "berhasil", "senang", "diperbaiki"),
        Emotion.CONFIDENT: ("pasti", "dikonfirmasi", "terverifikasi", "tentu"),
        Emotion.CURIOUS: ("menarik", "penasaran"),
        Emotion.CALM: ("tenang", "stabil"),
        Emotion.CONCERNED: ("peringatan", "hati-hati", "risiko", "bahaya"),
        Emotion.SERIOUS: ("kritis", "mendesak", "serius", "keamanan", "kerentanan"),
        Emotion.SAD: ("maaf", "sayangnya", "gagal", "kesalahan", "rusak", "hilang"),
    },
    ones=("nol", "satu", "dua", "tiga", "empat", "lima", "enam", "tujuh", "delapan", "sembilan",
          "sepuluh", "sebelas", "dua belas", "tiga belas", "empat belas", "lima belas",
          "enam belas", "tujuh belas", "delapan belas", "sembilan belas"),
    tens=("", "", "dua puluh", "tiga puluh", "empat puluh", "lima puluh",
          "enam puluh", "tujuh puluh", "delapan puluh", "sembilan puluh"),
    tens_rule=TensRule.TENS_FIRST,
    hundred="ratus",
    hundred_needs_one=True,
    hundreds=("", "seratus", "dua ratus", "tiga ratus", "empat ratus", "lima ratus",
              "enam ratus", "tujuh ratus", "delapan ratus", "sembilan ratus"),
    scales=((1_000_000, ("satu juta", "juta", "juta")), (1_000, ("seribu", "ribu", "ribu"))),
    point="koma",
    units={"%": ("persen", "persen"), "gb": ("gigabita", "gigabita")},
)

SWAHILI = LanguagePack(
    code="sw",
    label="Swahili",
    endonym="Kiswahili",
    negations=("si", "hapana", "hakuna", "bila", "kamwe"),
    intensifiers=("sana", "kabisa", "mno", "kweli"),
    hedges=("labda", "pengine", "inaonekana"),
    clause_breaks=("lakini", "ingawa", "hata hivyo"),
    cues={
        Emotion.EXCITED: ("ajabu", "bora", "nzuri sana", "kamili"),
        Emotion.HAPPY: ("nzuri", "asante", "mafanikio", "furaha", "imerekebishwa"),
        Emotion.CONFIDENT: ("hakika", "imethibitishwa", "bila shaka"),
        Emotion.CURIOUS: ("kuvutia", "udadisi"),
        Emotion.CALM: ("utulivu", "imara"),
        Emotion.CONCERNED: ("onyo", "hatari", "tahadhari"),
        Emotion.SERIOUS: ("muhimu", "dharura", "usalama"),
        Emotion.SAD: ("samahani", "kwa bahati mbaya", "imeshindwa", "hitilafu", "imevunjika"),
    },
    ones=("sifuri", "moja", "mbili", "tatu", "nne", "tano", "sita", "saba", "nane", "tisa",
          "kumi", "kumi na moja", "kumi na mbili", "kumi na tatu", "kumi na nne",
          "kumi na tano", "kumi na sita", "kumi na saba", "kumi na nane", "kumi na tisa"),
    tens=("", "", "ishirini", "thelathini", "arobaini", "hamsini", "sitini",
          "sabini", "themanini", "tisini"),
    tens_rule=TensRule.TENS_FIRST,
    compound=" na ",
    hundred="mia",
    hundred_needs_one=True,
    hundred_after=True,
    scales=((1_000_000, "milioni"), (1_000, "elfu")),
    scale_after=True,
    point="nukta",
    units={"%": ("asilimia", "asilimia"), "gb": ("gigabaiti", "gigabaiti")},
)

ASIA = (
    HINDI, NEPALI, MARATHI, BENGALI, GUJARATI, PUNJABI, TAMIL, TELUGU,
    KANNADA, MALAYALAM, SINHALA, URDU, ARABIC, HEBREW, PERSIAN, JAPANESE,
    CHINESE, KOREAN, THAI, VIETNAMESE, INDONESIAN, SWAHILI,
)
