/**
 * The document shell and global stylesheet are generated from TypeScript by
 * vite-plugins/aera-document.ts. These cover the properties the build relies
 * on, which used to be guaranteed only by hand-maintained index.html and
 * globals.css files sitting outside the component tree.
 */

import { describe, expect, it } from 'vitest';
import { renderDocument } from '@/document';
import { renderGlobalStyles } from '@design/globalStyles';
import { darkTheme, cssVarName, themes } from '@design/themes';
import { palette } from '@design/colors';

describe('document shell', () => {
  const html = renderDocument();

  it('provides the mount point index.tsx looks for', () => {
    expect(html).toContain('id="root"');
  });

  it('loads the module entry Vite needs as its Rollup input', () => {
    expect(html).toContain('type="module"');
    expect(html).toContain('/src/index.tsx');
  });

  it('takes the theme colour from the palette rather than a literal', () => {
    expect(html).toContain(`content="${palette.bg.base}"`);
  });

  it('links the favicon', () => {
    expect(html).toContain('favicon.png');
  });

  it('says it is generated, so nobody edits the output by hand', () => {
    expect(html).toContain('Generated by');
  });

  it('accepts an alternate entry, for tooling that relocates it', () => {
    expect(renderDocument({ entry: '/src/other.tsx' })).toContain('/src/other.tsx');
  });
});

describe('global stylesheet', () => {
  const css = renderGlobalStyles();

  it('imports tailwind first, or its layers are ordered wrongly', () => {
    const body = css.slice(css.indexOf("@import 'tailwindcss';"));
    expect(body.startsWith("@import 'tailwindcss';")).toBe(true);
  });

  it('declares an @theme block for Tailwind v4 tokens', () => {
    expect(css).toContain('@theme {');
    expect(css).toContain(`--color-accent: ${palette.accent.primary};`);
  });

  it('emits a boot default for every theme colour', () => {
    // Missing any one leaves that token unset until applyTheme() runs, so
    // the first paint would be unstyled.
    for (const [key, value] of Object.entries(darkTheme.colors)) {
      expect(css).toContain(`${cssVarName(key)}: ${value};`);
    }
  });

  it('cannot drift from the theme definitions', () => {
    // The :root block is generated from darkTheme, so every theme's keys are
    // represented; a renamed token changes both sides at once.
    const names = Object.keys(themes.dark.colors).map(cssVarName);
    expect(new Set(names).size).toBe(names.length);
    for (const name of names) expect(css).toContain(name);
  });

  it('defines the animations components reference by class', () => {
    for (const animation of [
      'animate-rise',
      'animate-spin-slow',
      'animate-pulse-slow',
      'animate-breathe',
      'animate-scan',
      'animate-glow',
    ]) {
      expect(css).toContain(`.${animation}`);
    }
  });

  it('honours prefers-reduced-motion', () => {
    expect(css).toContain('prefers-reduced-motion');
  });

  it('has no hard-coded violet left from the pre-cyan palette', () => {
    // aera-breathe kept a literal rgba(124, 92, 255) glow after the accent
    // moved to cyan, which is exactly the drift this file exists to prevent.
    expect(css).not.toContain('124, 92, 255');
  });
});
